### PR TITLE
Use truncate() of CleartextChannel when opening new Channel with `TRUNCATE_EXISTING`

### LINKED ISSUE #269: Truncating a channel which is currently written can create invalid ciphertext
## Summary
Library version: 2.7.1

Truncating a channel which is currently written to can create invalid ciphertext/unreadable file.

## Description
In our test suite exists a test, which truncates a file while another thread writes data to the same file:
https://github.com/cryptomator/cryptofs/blob/4d6a56b9c221511a4b6910bd44b5e023321e82e2/src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java#L620-L647

This test fails in very rare cases, e.g. in CI run [12694328432](https://github.com/cryptomator/cryptofs/actions/runs/12694328432). If the logs are not available anymore, you can download them [here](https://github.com/user-attachments/files/18380545/0_Build.and.Test.txt)

You can trigger the failure with higher probability, if you add a new line after line 634 with `Thread.sleep(2000);`.

### PR DESCRIPTION
**Pull request by infeo**
This PR fixes #269.

Instead of writing an "optimized", but wrong truncate block, we can simply use `CleartextChannel.truncate(0)` when opening a new file. Benefit of this method: It is already tested! And since it is synchronized and also creating a new file channel is synchronized, we can be sure that side calls cannot interfere.

### CODE REVIEW

File: src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java [hunk 1]
```diff
@@ -632,6 +632,7 @@ public void testConcurrentWriteAndTruncate() throws IOException {
 						buf.flip();
 					}
 				});
+				Thread.sleep(1000);
```
Comment (overheadhunter) [inline src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java:635]: To be removed for CI, rather use a barrier, countdownlatch, etc.

File: src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java [hunk 2]
```diff
@@ -93,19 +93,20 @@ public void testCloseImmediatelyIfOpeningFirstChannelFails() {
 	}
 
 	@Test
-	@DisplayName("Opening a file channel with TRUNCATE_EXISTING sets the file size to 0")
+	@DisplayName("Opening a file channel with TRUNCATE_EXISTING calls truncate(0) on the cleartextChannel")
 	public void testFileSizeZerodOnTruncateExisting() throws IOException {
```
Comment (overheadhunter) [inline src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java:97]: Method name misleading, since you removed the file size verification.

I assume file size is implicitly zeroed in the truncate call?

File: src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java [hunk 3]
```diff
@@ -70,15 +70,13 @@ public synchronized FileChannel newFileChannel(EffectiveOpenOptions options, Fil
 		try {
 			ciphertextFileChannel = path.getFileSystem().provider().newFileChannel(path, options.createOpenOptionsForEncryptedFile(), attrs);
 			initFileHeader(options, ciphertextFileChannel);
-			if (options.truncateExisting()) {
-				chunkCache.invalidateStale();
-				ciphertextFileChannel.truncate(cryptor.fileHeaderCryptor().headerSize());
-				fileSize.set(0);
-			}
 			initFileSize(ciphertextFileChannel);
```
Comment (overheadhunter) [inline src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java:73]: can be removed/replaced as well, can't it? The old ciphertextFileSize is most likely wrong at this point in time.

**Review by overheadhunter — CHANGES_REQUESTED** [review]
Good catch, did you spot it in the failed CI run?

**Comment by infeo** [comment]
> did you spot it in the failed CI run?

yes. I worked on a completely different feature (FileNameDecryptor) and was tempted to declare the failing build as a fluke. Luckily i decided to investigate the issue^^ We have tests for a reason!

File: src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java (hunk 3 above)
Comment (infeo) [reply src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java:73]: It could be replaced, but it is not related to the issue.
The method initializes the file size variable on any _newly_ opened file. If the filesize is already initatilizes, the method directly returns.

So, if we opened the first time a file and truncate it, it does not matter because we are inside a synchronized block and no other thread can read wrong information.
If it is not the first time (aka fileSize is already initialized), the method does nothing, which is also okay.

File: src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java (hunk 2 above)
Comment (infeo) [reply src/test/java/org/cryptomator/cryptofs/fh/OpenCryptoFileTest.java]: > I assume file size is implicitly zeroed in the truncate call?

Yes, but this is not the concern of this unit test any more. I renamed the method in https://github.com/cryptomator/cryptofs/pull/270/commits/38135c935e5da7c5bd55dfd6ea3ef70425257865

File: src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java (hunk 1 above)
Comment (infeo) [reply src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java]: Done in https://github.com/cryptomator/cryptofs/pull/270/commits/9d93701d58d827aeb5dfbe34148e8e75cfdf37b6

**Review by overheadhunter — APPROVED** [review]

File: src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java (hunk 1 above)
Comment (overheadhunter) [reply src/test/java/org/cryptomator/cryptofs/CryptoFileChannelWriteReadIntegrationTest.java]: for the record, I meant like in 5363d4b
